### ISSUE TITLE
Create a background process to change the appointment status to "NOT ASSISTED" in case the patient does not keep the appointment

### ISSUE THREAD

**Issue by MrDave1999** [DentallApp/back-end#65]
The background process can perform this task at night at 21:00 pm (this could be changed from a .env file). 
The advantage of this functionality is that the dentist no longer has to keep an eye on changing the appointment status in case the patient does not show up for the appointment.

**Comment by DevD4v3** [comment]
This feature will not be implemented, because I can't think of a way for the job to check if the appointment **was assisted or not.**
The dentist may forget to change the appointment status to Assisted, in case the patient attends the appointment, so Job(worker) would change the appointment to **Not Assisted** when this is not true.
