### ISSUE TITLE
Avoid repeating code in the `RootDialog` class

### ISSUE THREAD

**Issue by MrDave1999** [DentallApp/back-end#70]
The same code is repeated in these **steps**:
```cs
ShowNameOfOffices,
ShowNameOfServices,
ShowNameOfDentists,
ShowAppoinmentDate,
ShowSchedules
```

**Comment by DevD4v3** [comment]
I have decided not to perform any refactoring. Each method has its own responsibility and may represent different logic.
If try to apply the DRY principle to create only one method in order to reuse it at each step of the cascade dialog, this could cause a maintenance problem in the future if decide to add a different logic to some of the steps.
